// Code generated by "stringer -type=IsoCode639_3"; DO NOT EDIT.

package lingua

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AFR-0]
	_ = x[ARA-1]
	_ = x[AZE-2]
	_ = x[BEL-3]
	_ = x[BEN-4]
	_ = x[BOS-5]
	_ = x[BUL-6]
	_ = x[CAT-7]
	_ = x[CES-8]
	_ = x[CYM-9]
	_ = x[DAN-10]
	_ = x[DEU-11]
	_ = x[ELL-12]
	_ = x[ENG-13]
	_ = x[EPO-14]
	_ = x[EST-15]
	_ = x[EUS-16]
	_ = x[FAS-17]
	_ = x[FIN-18]
	_ = x[FRA-19]
	_ = x[GLE-20]
	_ = x[GUJ-21]
	_ = x[HEB-22]
	_ = x[HIN-23]
	_ = x[HRV-24]
	_ = x[HUN-25]
	_ = x[HYE-26]
	_ = x[IND-27]
	_ = x[ISL-28]
	_ = x[ITA-29]
	_ = x[JPN-30]
	_ = x[JPN_Latin-31]
	_ = x[KAT-32]
	_ = x[KAZ-33]
	_ = x[KOR-34]
	_ = x[KOR_Latin-35]
	_ = x[LAT-36]
	_ = x[LAV-37]
	_ = x[LIT-38]
	_ = x[LUG-39]
	_ = x[MAR-40]
	_ = x[MKD-41]
	_ = x[MON-42]
	_ = x[MRI-43]
	_ = x[MSA-44]
	_ = x[NLD-45]
	_ = x[NNO-46]
	_ = x[NOB-47]
	_ = x[PAN-48]
	_ = x[POL-49]
	_ = x[POR-50]
	_ = x[RON-51]
	_ = x[RUS-52]
	_ = x[SLK-53]
	_ = x[SLV-54]
	_ = x[SNA-55]
	_ = x[SOM-56]
	_ = x[SOT-57]
	_ = x[SPA-58]
	_ = x[SQI-59]
	_ = x[SRP-60]
	_ = x[SWA-61]
	_ = x[SWE-62]
	_ = x[TAM-63]
	_ = x[TEL-64]
	_ = x[TGL-65]
	_ = x[THA-66]
	_ = x[TSN-67]
	_ = x[TSO-68]
	_ = x[TUR-69]
	_ = x[UKR-70]
	_ = x[URD-71]
	_ = x[VIE-72]
	_ = x[XHO-73]
	_ = x[YOR-74]
	_ = x[ZHO-75]
	_ = x[ZUL-76]
	_ = x[UnknownIsoCode639_3-77]
}

const _IsoCode639_3_name = "AFRARAAZEBELBENBOSBULCATCESCYMDANDEUELLENGEPOESTEUSFASFINFRAGLEGUJHEBHINHRVHUNHYEINDISLITAJPNJPN_LatinKATKAZKORKOR_LatinLATLAVLITLUGMARMKDMONMRIMSANLDNNONOBPANPOLPORRONRUSSLKSLVSNASOMSOTSPASQISRPSWASWETAMTELTGLTHATSNTSOTURUKRURDVIEXHOYORZHOZULUnknownIsoCode639_3"

var _IsoCode639_3_index = [...]uint16{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 102, 105, 108, 111, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 262}

func (i IsoCode639_3) String() string {
	if i < 0 || i >= IsoCode639_3(len(_IsoCode639_3_index)-1) {
		return "IsoCode639_3(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IsoCode639_3_name[_IsoCode639_3_index[i]:_IsoCode639_3_index[i+1]]
}
