// Code generated by "stringer -type=Language"; DO NOT EDIT.

package lingua

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Afrikaans-0]
	_ = x[Albanian-1]
	_ = x[Arabic-2]
	_ = x[Armenian-3]
	_ = x[Azerbaijani-4]
	_ = x[Basque-5]
	_ = x[Belarusian-6]
	_ = x[Bengali-7]
	_ = x[Bokmal-8]
	_ = x[Bosnian-9]
	_ = x[Bulgarian-10]
	_ = x[Catalan-11]
	_ = x[Chinese-12]
	_ = x[Croatian-13]
	_ = x[Czech-14]
	_ = x[Danish-15]
	_ = x[Dutch-16]
	_ = x[English-17]
	_ = x[Esperanto-18]
	_ = x[Estonian-19]
	_ = x[Finnish-20]
	_ = x[French-21]
	_ = x[Ganda-22]
	_ = x[Georgian-23]
	_ = x[German-24]
	_ = x[Greek-25]
	_ = x[Gujarati-26]
	_ = x[Hebrew-27]
	_ = x[Hindi-28]
	_ = x[Hungarian-29]
	_ = x[Icelandic-30]
	_ = x[Indonesian-31]
	_ = x[Irish-32]
	_ = x[Italian-33]
	_ = x[Japanese-34]
	_ = x[JapaneseLatin-35]
	_ = x[Kazakh-36]
	_ = x[Korean-37]
	_ = x[KoreanLatin-38]
	_ = x[Latin-39]
	_ = x[Latvian-40]
	_ = x[Lithuanian-41]
	_ = x[Macedonian-42]
	_ = x[Malay-43]
	_ = x[Maori-44]
	_ = x[Marathi-45]
	_ = x[Mongolian-46]
	_ = x[Nynorsk-47]
	_ = x[Persian-48]
	_ = x[Polish-49]
	_ = x[Portuguese-50]
	_ = x[Punjabi-51]
	_ = x[Romanian-52]
	_ = x[Russian-53]
	_ = x[Serbian-54]
	_ = x[Shona-55]
	_ = x[Slovak-56]
	_ = x[Slovene-57]
	_ = x[Somali-58]
	_ = x[Sotho-59]
	_ = x[Spanish-60]
	_ = x[Swahili-61]
	_ = x[Swedish-62]
	_ = x[Tagalog-63]
	_ = x[Tamil-64]
	_ = x[Telugu-65]
	_ = x[Thai-66]
	_ = x[Tsonga-67]
	_ = x[Tswana-68]
	_ = x[Turkish-69]
	_ = x[Ukrainian-70]
	_ = x[Urdu-71]
	_ = x[Vietnamese-72]
	_ = x[Welsh-73]
	_ = x[Xhosa-74]
	_ = x[Yoruba-75]
	_ = x[Zulu-76]
	_ = x[Unknown-77]
}

const _Language_name = "AfrikaansAlbanianArabicArmenianAzerbaijaniBasqueBelarusianBengaliBokmalBosnianBulgarianCatalanChineseCroatianCzechDanishDutchEnglishEsperantoEstonianFinnishFrenchGandaGeorgianGermanGreekGujaratiHebrewHindiHungarianIcelandicIndonesianIrishItalianJapaneseJapaneseLatinKazakhKoreanKoreanLatinLatinLatvianLithuanianMacedonianMalayMaoriMarathiMongolianNynorskPersianPolishPortuguesePunjabiRomanianRussianSerbianShonaSlovakSloveneSomaliSothoSpanishSwahiliSwedishTagalogTamilTeluguThaiTsongaTswanaTurkishUkrainianUrduVietnameseWelshXhosaYorubaZuluUnknown"

var _Language_index = [...]uint16{0, 9, 17, 23, 31, 42, 48, 58, 65, 71, 78, 87, 94, 101, 109, 114, 120, 125, 132, 141, 149, 156, 162, 167, 175, 181, 186, 194, 200, 205, 214, 223, 233, 238, 245, 253, 266, 272, 278, 289, 294, 301, 311, 321, 326, 331, 338, 347, 354, 361, 367, 377, 384, 392, 399, 406, 411, 417, 424, 430, 435, 442, 449, 456, 463, 468, 474, 478, 484, 490, 497, 506, 510, 520, 525, 530, 536, 540, 547}

func (i Language) String() string {
	if i < 0 || i >= Language(len(_Language_index)-1) {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[i]:_Language_index[i+1]]
}
