// Code generated by "stringer -type=Language"; DO NOT EDIT.

package lingua

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Afrikaans-0]
	_ = x[Albanian-1]
	_ = x[Arabic-2]
	_ = x[Armenian-3]
	_ = x[Azerbaijani-4]
	_ = x[Basque-5]
	_ = x[Belarusian-6]
	_ = x[Bengali-7]
	_ = x[Bokmal-8]
	_ = x[Bosnian-9]
	_ = x[Bulgarian-10]
	_ = x[Catalan-11]
	_ = x[Chinese-12]
	_ = x[Croatian-13]
	_ = x[Czech-14]
	_ = x[Danish-15]
	_ = x[Dutch-16]
	_ = x[English-17]
	_ = x[Esperanto-18]
	_ = x[Estonian-19]
	_ = x[Finnish-20]
	_ = x[French-21]
	_ = x[Ganda-22]
	_ = x[Georgian-23]
	_ = x[German-24]
	_ = x[Greek-25]
	_ = x[Gujarati-26]
	_ = x[Hebrew-27]
	_ = x[Hindi-28]
	_ = x[Hungarian-29]
	_ = x[Icelandic-30]
	_ = x[Indonesian-31]
	_ = x[Irish-32]
	_ = x[Italian-33]
	_ = x[Japanese-34]
	_ = x[Kazakh-35]
	_ = x[Korean-36]
	_ = x[KoreanLatin-37]
	_ = x[Latin-38]
	_ = x[Latvian-39]
	_ = x[Lithuanian-40]
	_ = x[Macedonian-41]
	_ = x[Malay-42]
	_ = x[Maori-43]
	_ = x[Marathi-44]
	_ = x[Mongolian-45]
	_ = x[Nynorsk-46]
	_ = x[Persian-47]
	_ = x[Polish-48]
	_ = x[Portuguese-49]
	_ = x[Punjabi-50]
	_ = x[Romanian-51]
	_ = x[Russian-52]
	_ = x[Serbian-53]
	_ = x[Shona-54]
	_ = x[Slovak-55]
	_ = x[Slovene-56]
	_ = x[Somali-57]
	_ = x[Sotho-58]
	_ = x[Spanish-59]
	_ = x[Swahili-60]
	_ = x[Swedish-61]
	_ = x[Tagalog-62]
	_ = x[Tamil-63]
	_ = x[Telugu-64]
	_ = x[Thai-65]
	_ = x[Tsonga-66]
	_ = x[Tswana-67]
	_ = x[Turkish-68]
	_ = x[Ukrainian-69]
	_ = x[Urdu-70]
	_ = x[Vietnamese-71]
	_ = x[Welsh-72]
	_ = x[Xhosa-73]
	_ = x[Yoruba-74]
	_ = x[Zulu-75]
	_ = x[Unknown-76]
}

const _Language_name = "AfrikaansAlbanianArabicArmenianAzerbaijaniBasqueBelarusianBengaliBokmalBosnianBulgarianCatalanChineseCroatianCzechDanishDutchEnglishEsperantoEstonianFinnishFrenchGandaGeorgianGermanGreekGujaratiHebrewHindiHungarianIcelandicIndonesianIrishItalianJapaneseKazakhKoreanKoreanLatinLatinLatvianLithuanianMacedonianMalayMaoriMarathiMongolianNynorskPersianPolishPortuguesePunjabiRomanianRussianSerbianShonaSlovakSloveneSomaliSothoSpanishSwahiliSwedishTagalogTamilTeluguThaiTsongaTswanaTurkishUkrainianUrduVietnameseWelshXhosaYorubaZuluUnknown"

var _Language_index = [...]uint16{0, 9, 17, 23, 31, 42, 48, 58, 65, 71, 78, 87, 94, 101, 109, 114, 120, 125, 132, 141, 149, 156, 162, 167, 175, 181, 186, 194, 200, 205, 214, 223, 233, 238, 245, 253, 259, 265, 276, 281, 288, 298, 308, 313, 318, 325, 334, 341, 348, 354, 364, 371, 379, 386, 393, 398, 404, 411, 417, 422, 429, 436, 443, 450, 455, 461, 465, 471, 477, 484, 493, 497, 507, 512, 517, 523, 527, 534}

func (i Language) String() string {
	if i < 0 || i >= Language(len(_Language_index)-1) {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[i]:_Language_index[i+1]]
}
